# Generated by Django 5.0.10 on 2025-04-06 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='diachi',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donhang',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ngaydathang',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donhang',
            name='sdt',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='donhang',
            name='tenkhach',
            field=models.CharField(default='', max_length=255),
        ),
    ]
