# Generated by Django 5.0.10 on 2025-04-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_donhang_diachi_donhang_email_donhang_ngaydathang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='diachi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='sdt',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='tenkhach',
            field=models.CharField(max_length=255),
        ),
    ]
