# Generated by Django 5.0.10 on 2025-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_donhang_diachi_alter_donhang_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ghichu',
            field=models.CharField(default='', max_length=300),
        ),
    ]
